#travis configuration 
dist: xenial
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export OS=linux && export mCC=gcc-7 && export mCXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
# nothing so far


before_script: 
- cd ${TRAVIS_BUILD_DIR}

# Compiler selection
compiler:
  - gcc

# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - make check
  
  # checkout dependencies
  - git clone --single-branch --branch M104 --depth 1 https://github.com/maker99/qmk_firmware
  
  # prepare the build environment 
  - cd ${TRAVIS_BUILD_DIR}/zeal60
  - ln -s ../qmk_firmware/keyboards
  - ln -s ../qmk_firmware/quantum
  - ln -s ../hidapi/hidapi
  
  - make zealM104


after_success:
- ls -alh 
- echo done
