#travis configuration 
language: c

#sudo: false # only for faster builds

install:
# nothing so far


before_script: 
- cd ${TRAVIS_BUILD_DIR}

# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/maker99/qmk_firmware.git
  - cd qmk_firmware
  - git checkout M104
  - ls -alh keyboards/M/M104
  - cd ${TRAVIS_BUILD_DIR}/zeal60
  - ls -alh
  #- make zeal60


after_success:
- ls -alh 
- echo done
