#travis configuration 
dist: xenial
language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
# nothing so far


before_script: 
- cd ${TRAVIS_BUILD_DIR}

# Compiler selection
compiler:
  - gcc


# Build steps
script: 
  # checkout dependencies
  - cd ${TRAVIS_BUILD_DIR}
  - gcc --version
  - g++ --version
  - ${CC} --version
  - ${CXX} --version
  #- git clone https://github.com/maker99/qmk_firmware.git
  - git clone --single-branch --branch M104 --depth 1 https://github.com/maker99/qmk_firmware
  
  # prepare the build environment 
  - cd ${TRAVIS_BUILD_DIR}/zeal60
  - ln -s ../qmk_firmware/keyboards
  - ln -s ../qmk_firmware/quantum
  - ln -s ../hidapi/hidapi

  #- make zeal60
  - cd ${TRAVIS_BUILD_DIR}/zeal60
  - ls -alh
  - make zealM104


after_success:
- ls -alh 
- echo done
