#travis configuration 
language: c

#sudo: false # only for faster builds

install:
# nothing so far


before_script: 
- cd ${TRAVIS_BUILD_DIR}

# Compiler selection
compiler:
  - gcc


# Build steps
script: 
  # checkout dependencies
  - cd ${TRAVIS_BUILD_DIR}
  #- git clone https://github.com/maker99/qmk_firmware.git
  - git clone --single-branch --branch M104 --depth 1 --no-checkout --filter=blob:none https://github.com/maker99/qmk_firmware
  - cd qmk_firmware 
  - git checkout -- keyboards/M
  - git checkout -- quantum
  - ls -alh keyboards
  - ls -alh
  - git clone https://github.com/signal11/hidapi.git
  - ls -alh hidapi
  
  # prepare the build environment 
  - cd ${TRAVIS_BUILD_DIR}/zeal60
  - ln -s ../qmk_firmware/keyboards
  - ln -s ../qmk_firmware/quantum
  - ln -s ../hidapi

  - ls -alh
  #- make zeal60
  
  # prepare for M104
  - cd ${TRAVIS_BUILD_DIR}/qmk_firmware
  - git checkout M104
  - ls -alh keyboards/M/M104
  - cd ${TRAVIS_BUILD_DIR}/zeal60
  #- make zeal60


after_success:
- ls -alh 
- echo done
